// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/edp-variants/CommandCenter.tsx": () => import("../components/mockups/edp-variants/CommandCenter.tsx"),
  "./components/mockups/edp-variants/PrecisionLight.tsx": () => import("../components/mockups/edp-variants/PrecisionLight.tsx"),
  "./components/mockups/edp-variants/WarmEnterprise.tsx": () => import("../components/mockups/edp-variants/WarmEnterprise.tsx")
};
